name: Sync 02 branches

on:
  push:
    branches:
      - dev
      - stage

jobs:
  sync-dev02:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Check out dev02 branch
        run: git checkout dev02

      - name: Merge dev into dev02 with theirs strategy
        run: git merge origin/dev --strategy-option theirs --allow-unrelated-histories

      - name: Push changes to dev02
        run: git push origin dev02

  sync-stage02:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/stage'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Check out stage02 branch
        run: git checkout stage02

      - name: Merge stage into stage02 with theirs strategy
        run: git merge origin/stage --strategy-option theirs --allow-unrelated-histories

      - name: Push changes to stage02
        run: git push origin stage02
