name: Test Secret Access
on:
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check if CCI_TOKEN exists
        run: |
          if [ -n "${{ secrets.CCI_TOKEN }}" ]; then
            echo "CCI_TOKEN is set (length: ${#CCI_TOKEN})"
          else
            echo "CCI_TOKEN is null or empty"
          fi
      
      - name: List all secrets (names only)
        run: |
          echo "Available secrets:"
          # This will show secret names but not values
          echo "CCI_TOKEN: ${{ secrets.CCI_TOKEN != '' && 'SET' || 'NOT SET' }}" 
