name: Update PR Description

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  update-description:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Details
        id: pr-details
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const details = {
              base: pr.base.ref,
              head: pr.head.ref
            };
            core.setOutput('base', details.base);
            core.setOutput('head', details.head);

      - name: Update PR Description
        uses: actions/github-script@v6
        with:
          script: |
            const baseBranch = '${{ steps.pr-details.outputs.base }}';
            const targetBranch = '${{ steps.pr-details.outputs.head }}';

            const updatedBody = context.payload.pull_request.body
              .replace('<BASE_BRANCH>', baseBranch)
              .replace('<TARGET_BRANCH>', targetBranch);

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: updatedBody
            });
