name: Update PR Description

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  update-description:
    runs-on: ubuntu-latest
    steps:
      - name: Update PR Description
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const baseBranch = pr.base.ref;
            const targetBranch = pr.head.ref;

            const updatedBody = context.payload.pull_request.body
              .replace('<BASE_BRANCH>', baseBranch)
              .replace('<TARGET_BRANCH>', targetBranch);

            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: updatedBody,
            });
