name: Update PR Description

on:
  pull_request:
    types: [opened, edited]

jobs:
  update-description:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Details
        id: pr-details
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            return { base: pr.base.ref, head: pr.head.ref };
        result-encoding: string

      - name: Debug PR Details
        run: echo "PR Details: ${{ steps.pr-details.outputs.result }}"

      - name: Update PR Description
        uses: actions/github-script@v6
        with:
          script: |
            const prDetails = JSON.parse(core.getInput('pr-details'));
            const baseBranch = prDetails.base;
            const targetBranch = prDetails.head;

            const updatedBody = context.payload.pull_request.body
              .replace('<BASE_BRANCH>', baseBranch)
              .replace('<TARGET_BRANCH>', targetBranch);

            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: updatedBody,
            });
        env:
          pr-details: ${{ steps.pr-details.outputs.result }}
